In [1]:
from game import Game
from position import Position
from board import Board
from board import pretty_print_bb as pprint
from constants import Piece, SquarePosition as sq
from move import Move

import numpy as np

In [2]:
game = Game()

In [3]:
game.get_current_position().__dict__

{'board': <board.Board at 0x102e62280>,
 'to_move': 0,
 'castle_rights': {0: True, 1: True},
 'en_passant_target': None,
 'halfmove_clock': 0,
 'piece_map': {1: {8, 9, 10, 11, 12, 13, 14, 15},
  2: {0, 7},
  3: {1, 6},
  4: {2, 5},
  5: {3},
  6: {4},
  7: {48, 49, 50, 51, 52, 53, 54, 55},
  8: {56, 63},
  9: {57, 62},
  10: {58, 61},
  11: {59},
  12: {60}}}

In [4]:
position = game.get_current_position()
position.board

In [5]:
pprint(position.board.white_pieces_bb)

8  ░ ░ ░ ░ ░ ░ ░ ░
7  ░ ░ ░ ░ ░ ░ ░ ░
6  ░ ░ ░ ░ ░ ░ ░ ░
5  ░ ░ ░ ░ ░ ░ ░ ░
4  ░ ░ ░ ░ ░ ░ ░ ░
3  ░ ░ ░ ░ ░ ░ ░ ░
2  ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓
1  ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓
   A B C D E F G H


In [6]:
pprint(position.board.black_pieces_bb)
pprint(position.board.white_pieces_bb | position.board.black_pieces_bb)

8  ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓
7  ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓
6  ░ ░ ░ ░ ░ ░ ░ ░
5  ░ ░ ░ ░ ░ ░ ░ ░
4  ░ ░ ░ ░ ░ ░ ░ ░
3  ░ ░ ░ ░ ░ ░ ░ ░
2  ░ ░ ░ ░ ░ ░ ░ ░
1  ░ ░ ░ ░ ░ ░ ░ ░
   A B C D E F G H
8  ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓
7  ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓
6  ░ ░ ░ ░ ░ ░ ░ ░
5  ░ ░ ░ ░ ░ ░ ░ ░
4  ░ ░ ░ ░ ░ ░ ░ ░
3  ░ ░ ░ ░ ░ ░ ░ ░
2  ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓
1  ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓
   A B C D E F G H


In [7]:
position = game.get_current_position()
position.piece_map

{1: {8, 9, 10, 11, 12, 13, 14, 15},
 2: {0, 7},
 3: {1, 6},
 4: {2, 5},
 5: {3},
 6: {4},
 7: {48, 49, 50, 51, 52, 53, 54, 55},
 8: {56, 63},
 9: {57, 62},
 10: {58, 61},
 11: {59},
 12: {60}}

In [8]:
move = Move(Piece.wP, (sq.e2, sq.e4), False, False)
position.make_move(move)

'-- TODO: generate FEN --'

In [9]:
position.board.white_pieces_bb

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int8)

In [10]:
pprint(position.board.occupied_squares_bb)

8  ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓
7  ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓
6  ░ ░ ░ ░ ░ ░ ░ ░
5  ░ ░ ░ ░ ░ ░ ░ ░
4  ░ ░ ░ ░ ▓ ░ ░ ░
3  ░ ░ ░ ░ ░ ░ ░ ░
2  ▓ ▓ ▓ ▓ ░ ▓ ▓ ▓
1  ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓
   A B C D E F G H


In [11]:
move = Move(Piece.bP, (sq.e7, sq.e5), False, False)
position.make_move(move)

'-- TODO: generate FEN --'

In [12]:
pprint(position.board.occupied_squares_bb)

8  ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓
7  ▓ ▓ ▓ ▓ ░ ▓ ▓ ▓
6  ░ ░ ░ ░ ░ ░ ░ ░
5  ░ ░ ░ ░ ▓ ░ ░ ░
4  ░ ░ ░ ░ ▓ ░ ░ ░
3  ░ ░ ░ ░ ░ ░ ░ ░
2  ▓ ▓ ▓ ▓ ░ ▓ ▓ ▓
1  ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓
   A B C D E F G H


In [13]:
move = Move(Piece.wN, (sq.g1, sq.f3), False, False)
position.make_move(move)

'-- TODO: generate FEN --'

In [14]:
pprint(position.board.occupied_squares_bb)

8  ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓
7  ▓ ▓ ▓ ▓ ░ ▓ ▓ ▓
6  ░ ░ ░ ░ ░ ░ ░ ░
5  ░ ░ ░ ░ ▓ ░ ░ ░
4  ░ ░ ░ ░ ▓ ░ ░ ░
3  ░ ░ ░ ░ ░ ▓ ░ ░
2  ▓ ▓ ▓ ▓ ░ ▓ ▓ ▓
1  ▓ ▓ ▓ ▓ ▓ ▓ ░ ▓
   A B C D E F G H


In [15]:
move = Move(Piece.bN, (sq.b8, sq.c6), False, False)
position.make_move(move)
pprint(position.board.occupied_squares_bb)

8  ▓ ░ ▓ ▓ ▓ ▓ ▓ ▓
7  ▓ ▓ ▓ ▓ ░ ▓ ▓ ▓
6  ░ ░ ▓ ░ ░ ░ ░ ░
5  ░ ░ ░ ░ ▓ ░ ░ ░
4  ░ ░ ░ ░ ▓ ░ ░ ░
3  ░ ░ ░ ░ ░ ▓ ░ ░
2  ▓ ▓ ▓ ▓ ░ ▓ ▓ ▓
1  ▓ ▓ ▓ ▓ ▓ ▓ ░ ▓
   A B C D E F G H


In [16]:
move = Move(Piece.wB, (sq.f1, sq.b5), False, False)
position.make_move(move)
pprint(position.board.occupied_squares_bb)

8  ▓ ░ ▓ ▓ ▓ ▓ ▓ ▓
7  ▓ ▓ ▓ ▓ ░ ▓ ▓ ▓
6  ░ ░ ▓ ░ ░ ░ ░ ░
5  ░ ▓ ░ ░ ▓ ░ ░ ░
4  ░ ░ ░ ░ ▓ ░ ░ ░
3  ░ ░ ░ ░ ░ ▓ ░ ░
2  ▓ ▓ ▓ ▓ ░ ▓ ▓ ▓
1  ▓ ▓ ▓ ▓ ▓ ░ ░ ▓
   A B C D E F G H


In [17]:
move = Move(Piece.bP, (sq.a7, sq.a6), False, False)
position.make_move(move)
pprint(position.board.occupied_squares_bb)

8  ▓ ░ ▓ ▓ ▓ ▓ ▓ ▓
7  ░ ▓ ▓ ▓ ░ ▓ ▓ ▓
6  ▓ ░ ▓ ░ ░ ░ ░ ░
5  ░ ▓ ░ ░ ▓ ░ ░ ░
4  ░ ░ ░ ░ ▓ ░ ░ ░
3  ░ ░ ░ ░ ░ ▓ ░ ░
2  ▓ ▓ ▓ ▓ ░ ▓ ▓ ▓
1  ▓ ▓ ▓ ▓ ▓ ░ ░ ▓
   A B C D E F G H


In [18]:
move = Move(Piece.wB, (sq.b5, sq.a4), False, False)
position.make_move(move)
pprint(position.board.occupied_squares_bb)

8  ▓ ░ ▓ ▓ ▓ ▓ ▓ ▓
7  ░ ▓ ▓ ▓ ░ ▓ ▓ ▓
6  ▓ ░ ▓ ░ ░ ░ ░ ░
5  ░ ░ ░ ░ ▓ ░ ░ ░
4  ▓ ░ ░ ░ ▓ ░ ░ ░
3  ░ ░ ░ ░ ░ ▓ ░ ░
2  ▓ ▓ ▓ ▓ ░ ▓ ▓ ▓
1  ▓ ▓ ▓ ▓ ▓ ░ ░ ▓
   A B C D E F G H


In [19]:
move = Move(Piece.bP, (sq.b7, sq.b5), False, False)
position.make_move(move)
pprint(position.board.occupied_squares_bb)

8  ▓ ░ ▓ ▓ ▓ ▓ ▓ ▓
7  ░ ░ ▓ ▓ ░ ▓ ▓ ▓
6  ▓ ░ ▓ ░ ░ ░ ░ ░
5  ░ ▓ ░ ░ ▓ ░ ░ ░
4  ▓ ░ ░ ░ ▓ ░ ░ ░
3  ░ ░ ░ ░ ░ ▓ ░ ░
2  ▓ ▓ ▓ ▓ ░ ▓ ▓ ▓
1  ▓ ▓ ▓ ▓ ▓ ░ ░ ▓
   A B C D E F G H


In [20]:
move = Move(Piece.wB, (sq.a4, sq.b3), False, False)
position.make_move(move)
pprint(position.board.occupied_squares_bb)

8  ▓ ░ ▓ ▓ ▓ ▓ ▓ ▓
7  ░ ░ ▓ ▓ ░ ▓ ▓ ▓
6  ▓ ░ ▓ ░ ░ ░ ░ ░
5  ░ ▓ ░ ░ ▓ ░ ░ ░
4  ░ ░ ░ ░ ▓ ░ ░ ░
3  ░ ▓ ░ ░ ░ ▓ ░ ░
2  ▓ ▓ ▓ ▓ ░ ▓ ▓ ▓
1  ▓ ▓ ▓ ▓ ▓ ░ ░ ▓
   A B C D E F G H


In [21]:
move = Move(Piece.bN, (sq.g8, sq.f6), False, False)
position.make_move(move)
pprint(position.board.occupied_squares_bb)

8  ▓ ░ ▓ ▓ ▓ ▓ ░ ▓
7  ░ ░ ▓ ▓ ░ ▓ ▓ ▓
6  ▓ ░ ▓ ░ ░ ▓ ░ ░
5  ░ ▓ ░ ░ ▓ ░ ░ ░
4  ░ ░ ░ ░ ▓ ░ ░ ░
3  ░ ▓ ░ ░ ░ ▓ ░ ░
2  ▓ ▓ ▓ ▓ ░ ▓ ▓ ▓
1  ▓ ▓ ▓ ▓ ▓ ░ ░ ▓
   A B C D E F G H


In [22]:
u = np.zeros(64, dtype="byte")
u[12] = 1
pprint(u)

8  ░ ░ ░ ░ ░ ░ ░ ░
7  ░ ░ ░ ░ ░ ░ ░ ░
6  ░ ░ ░ ░ ░ ░ ░ ░
5  ░ ░ ░ ░ ░ ░ ░ ░
4  ░ ░ ░ ░ ░ ░ ░ ░
3  ░ ░ ░ ░ ░ ░ ░ ░
2  ░ ░ ░ ░ ▓ ░ ░ ░
1  ░ ░ ░ ░ ░ ░ ░ ░
   A B C D E F G H


In [23]:
u[12+9] = 1
u[12+7] = 1

pprint(u)

8  ░ ░ ░ ░ ░ ░ ░ ░
7  ░ ░ ░ ░ ░ ░ ░ ░
6  ░ ░ ░ ░ ░ ░ ░ ░
5  ░ ░ ░ ░ ░ ░ ░ ░
4  ░ ░ ░ ░ ░ ░ ░ ░
3  ░ ░ ░ ▓ ░ ▓ ░ ░
2  ░ ░ ░ ░ ▓ ░ ░ ░
1  ░ ░ ░ ░ ░ ░ ░ ░
   A B C D E F G H


In [24]:
u = np.zeros(64, dtype="byte")
u[12] = 1
u[27] = 1
x = np.packbits(u)

In [25]:
u

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int8)

In [26]:
x

array([ 0,  8,  0, 16,  0,  0,  0,  0], dtype=uint8)

### Try np.int64 bibtboard size 1

In [55]:
bitboard = np.zeros(1, dtype=np.uint64)

In [56]:
bitboard.tobytes()

b'\x00\x00\x00\x00\x00\x00\x00\x00'

In [57]:
bitboard[0] = 123983

In [58]:
from sys import getsizeof
getsizeof(bitboard)

104

In [59]:
getsizeof(position.board.white_pieces_bb)

160

In [60]:
bitboard[0]

123983

In [65]:
import string

def get_binary_string(bb):
    return format(bb[0], 'b').zfill(64)


bitboard = np.zeros(1, dtype=np.uint64)
board_size = 8

def pprint_bb(bb):
    bb = get_binary_string(bb)
    val = ''
    display_rank = board_size
    board = [bb[i:i+board_size] for i in range(0, len(bb), board_size)]
    for i, row in enumerate(board):
        val += f'{display_rank} '
        display_rank -= 1
        for square in reversed(row):
            if int(square):
                val += ' ▓'
                continue
            val += ' ░'
        val += '\n'
    val += '  '
    for char in string.ascii_uppercase[:board_size]:
        val += f' {char}'
    print(val)

In [66]:
pprint_bb(bitboard)

8  ░ ░ ░ ░ ░ ░ ░ ░
7  ░ ░ ░ ░ ░ ░ ░ ░
6  ░ ░ ░ ░ ░ ░ ░ ░
5  ░ ░ ░ ░ ░ ░ ░ ░
4  ░ ░ ░ ░ ░ ░ ░ ░
3  ░ ░ ░ ░ ░ ░ ░ ░
2  ░ ░ ░ ░ ░ ░ ░ ░
1  ░ ░ ░ ░ ░ ░ ░ ░
   A B C D E F G H


In [35]:
bitboard | 1 << 64

array([18446744073709551616], dtype=object)

In [36]:
np.bitwise_or(bitboard, 1 << 63)

array([9223372036854775808], dtype=uint64)

In [37]:
def set_bit(value, bit):
    return value | (1<<bit)

def clear_bit(value, bit):
    return value & ~(1<<bit)

In [38]:
pprint_bb(bitboard | 1 << 63)

8  ░ ░ ░ ░ ░ ░ ░ ▓
7  ░ ░ ░ ░ ░ ░ ░ ░
6  ░ ░ ░ ░ ░ ░ ░ ░
5  ░ ░ ░ ░ ░ ░ ░ ░
4  ░ ░ ░ ░ ░ ░ ░ ░
3  ░ ░ ░ ░ ░ ░ ░ ░
2  ░ ░ ░ ░ ░ ░ ░ ░
1  ░ ░ ░ ░ ░ ░ ░ ░
   A B C D E F G H


In [39]:
bitboard | 1 << 63

array([9223372036854775808], dtype=uint64)

In [40]:
pprint_bb(set_bit(bitboard, 2))

8  ░ ░ ░ ░ ░ ░ ░ ░
7  ░ ░ ░ ░ ░ ░ ░ ░
6  ░ ░ ░ ░ ░ ░ ░ ░
5  ░ ░ ░ ░ ░ ░ ░ ░
4  ░ ░ ░ ░ ░ ░ ░ ░
3  ░ ░ ░ ░ ░ ░ ░ ░
2  ░ ░ ░ ░ ░ ░ ░ ░
1  ░ ░ ▓ ░ ░ ░ ░ ░
   A B C D E F G H


In [41]:
for bit in range(0,8):
    bitboard |= set_bit(bitboard, bit)

In [42]:
pprint_bb(bitboard)

8  ░ ░ ░ ░ ░ ░ ░ ░
7  ░ ░ ░ ░ ░ ░ ░ ░
6  ░ ░ ░ ░ ░ ░ ░ ░
5  ░ ░ ░ ░ ░ ░ ░ ░
4  ░ ░ ░ ░ ░ ░ ░ ░
3  ░ ░ ░ ░ ░ ░ ░ ░
2  ░ ░ ░ ░ ░ ░ ░ ░
1  ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓
   A B C D E F G H
