In [33]:
import numpy as np
from board import Board, pretty_print_bb
from constants import SquarePosition as sq
from game import Game
from position import Position

In [2]:
board = Board()

In [3]:
state = board.update_occupied_squares_bb()

In [4]:
pretty_print_bb(board.occupied_squares_bb)

8  ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓
7  ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓
6  ░ ░ ░ ░ ░ ░ ░ ░
5  ░ ░ ░ ░ ░ ░ ░ ░
4  ░ ░ ░ ░ ░ ░ ░ ░
3  ░ ░ ░ ░ ░ ░ ░ ░
2  ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓
1  ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓
   A B C D E F G H


In [5]:
white_pawns = board.white_P_bb
white_king = board.white_K_bb

In [6]:
pretty_print_bb(white_pawns)

8  ░ ░ ░ ░ ░ ░ ░ ░
7  ░ ░ ░ ░ ░ ░ ░ ░
6  ░ ░ ░ ░ ░ ░ ░ ░
5  ░ ░ ░ ░ ░ ░ ░ ░
4  ░ ░ ░ ░ ░ ░ ░ ░
3  ░ ░ ░ ░ ░ ░ ░ ░
2  ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓
1  ░ ░ ░ ░ ░ ░ ░ ░
   A B C D E F G H


In [7]:
pretty_print_bb(white_king)

8  ░ ░ ░ ░ ░ ░ ░ ░
7  ░ ░ ░ ░ ░ ░ ░ ░
6  ░ ░ ░ ░ ░ ░ ░ ░
5  ░ ░ ░ ░ ░ ░ ░ ░
4  ░ ░ ░ ░ ░ ░ ░ ░
3  ░ ░ ░ ░ ░ ░ ░ ░
2  ░ ░ ░ ░ ░ ░ ░ ░
1  ░ ░ ░ ░ ▓ ░ ░ ░
   A B C D E F G H


In [8]:
pretty_print_bb(board.black_R_bb)

8  ▓ ░ ░ ░ ░ ░ ░ ▓
7  ░ ░ ░ ░ ░ ░ ░ ░
6  ░ ░ ░ ░ ░ ░ ░ ░
5  ░ ░ ░ ░ ░ ░ ░ ░
4  ░ ░ ░ ░ ░ ░ ░ ░
3  ░ ░ ░ ░ ░ ░ ░ ░
2  ░ ░ ░ ░ ░ ░ ░ ░
1  ░ ░ ░ ░ ░ ░ ░ ░
   A B C D E F G H


In [9]:
pretty_print_bb(board.get_empty_squares_bb())

8  ░ ░ ░ ░ ░ ░ ░ ░
7  ░ ░ ░ ░ ░ ░ ░ ░
6  ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓
5  ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓
4  ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓
3  ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓
2  ░ ░ ░ ░ ░ ░ ░ ░
1  ░ ░ ░ ░ ░ ░ ░ ░
   A B C D E F G H


In [10]:
pretty_print_bb(board.queenside_bb)
pretty_print_bb(board.kingside_bb)
pretty_print_bb(board.center_files_bb)
pretty_print_bb(board.center_bb)
pretty_print_bb(board.flanks_bb)

8  ▓ ▓ ▓ ▓ ░ ░ ░ ░
7  ▓ ▓ ▓ ▓ ░ ░ ░ ░
6  ▓ ▓ ▓ ▓ ░ ░ ░ ░
5  ▓ ▓ ▓ ▓ ░ ░ ░ ░
4  ▓ ▓ ▓ ▓ ░ ░ ░ ░
3  ▓ ▓ ▓ ▓ ░ ░ ░ ░
2  ▓ ▓ ▓ ▓ ░ ░ ░ ░
1  ▓ ▓ ▓ ▓ ░ ░ ░ ░
   A B C D E F G H
8  ░ ░ ░ ░ ▓ ▓ ▓ ▓
7  ░ ░ ░ ░ ▓ ▓ ▓ ▓
6  ░ ░ ░ ░ ▓ ▓ ▓ ▓
5  ░ ░ ░ ░ ▓ ▓ ▓ ▓
4  ░ ░ ░ ░ ▓ ▓ ▓ ▓
3  ░ ░ ░ ░ ▓ ▓ ▓ ▓
2  ░ ░ ░ ░ ▓ ▓ ▓ ▓
1  ░ ░ ░ ░ ▓ ▓ ▓ ▓
   A B C D E F G H
8  ░ ░ ▓ ▓ ▓ ▓ ░ ░
7  ░ ░ ▓ ▓ ▓ ▓ ░ ░
6  ░ ░ ▓ ▓ ▓ ▓ ░ ░
5  ░ ░ ▓ ▓ ▓ ▓ ░ ░
4  ░ ░ ▓ ▓ ▓ ▓ ░ ░
3  ░ ░ ▓ ▓ ▓ ▓ ░ ░
2  ░ ░ ▓ ▓ ▓ ▓ ░ ░
1  ░ ░ ▓ ▓ ▓ ▓ ░ ░
   A B C D E F G H
8  ░ ░ ░ ░ ░ ░ ░ ░
7  ░ ░ ░ ░ ░ ░ ░ ░
6  ░ ░ ░ ░ ░ ░ ░ ░
5  ░ ░ ░ ▓ ▓ ░ ░ ░
4  ░ ░ ░ ▓ ▓ ░ ░ ░
3  ░ ░ ░ ░ ░ ░ ░ ░
2  ░ ░ ░ ░ ░ ░ ░ ░
1  ░ ░ ░ ░ ░ ░ ░ ░
   A B C D E F G H
8  ▓ ░ ░ ░ ░ ░ ░ ▓
7  ▓ ░ ░ ░ ░ ░ ░ ▓
6  ▓ ░ ░ ░ ░ ░ ░ ▓
5  ▓ ░ ░ ░ ░ ░ ░ ▓
4  ▓ ░ ░ ░ ░ ░ ░ ▓
3  ▓ ░ ░ ░ ░ ░ ░ ▓
2  ▓ ░ ░ ░ ░ ░ ░ ▓
1  ▓ ░ ░ ░ ░ ░ ░ ▓
   A B C D E F G H


In [11]:
board.plus1(sq.a1)

In [12]:
pretty_print_bb(board.bb)

8  ░ ░ ░ ░ ░ ░ ░ ░
7  ░ ░ ░ ░ ░ ░ ░ ░
6  ░ ░ ░ ░ ░ ░ ░ ░
5  ░ ░ ░ ░ ░ ░ ░ ░
4  ░ ░ ░ ░ ░ ░ ░ ░
3  ░ ░ ░ ░ ░ ░ ░ ░
2  ░ ░ ░ ░ ░ ░ ░ ░
1  ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓
   A B C D E F G H


In [13]:
board.reset_bb()
board.plus7(sq.f4)
pretty_print_bb(board.bb)

8  ░ ▓ ░ ░ ░ ░ ░ ░
7  ░ ░ ▓ ░ ░ ░ ░ ░
6  ░ ░ ░ ▓ ░ ░ ░ ░
5  ░ ░ ░ ░ ▓ ░ ░ ░
4  ░ ░ ░ ░ ░ ▓ ░ ░
3  ░ ░ ░ ░ ░ ░ ░ ░
2  ░ ░ ░ ░ ░ ░ ░ ░
1  ░ ░ ░ ░ ░ ░ ░ ░
   A B C D E F G H


In [14]:
board.reset_bb()
board.plus8(sq.f4)
pretty_print_bb(board.bb)

8  ░ ░ ░ ░ ░ ▓ ░ ░
7  ░ ░ ░ ░ ░ ▓ ░ ░
6  ░ ░ ░ ░ ░ ▓ ░ ░
5  ░ ░ ░ ░ ░ ▓ ░ ░
4  ░ ░ ░ ░ ░ ▓ ░ ░
3  ░ ░ ░ ░ ░ ░ ░ ░
2  ░ ░ ░ ░ ░ ░ ░ ░
1  ░ ░ ░ ░ ░ ░ ░ ░
   A B C D E F G H


In [15]:
board.reset_bb()
board.plus9(sq.f4)
pretty_print_bb(board.bb)
board.reset_bb()
board.plus9(sq.a1)
pretty_print_bb(board.bb)
board.reset_bb()
board.plus9(sq.b4)
pretty_print_bb(board.bb)

8  ░ ░ ░ ░ ░ ░ ░ ░
7  ░ ░ ░ ░ ░ ░ ░ ░
6  ░ ░ ░ ░ ░ ░ ░ ▓
5  ░ ░ ░ ░ ░ ░ ▓ ░
4  ░ ░ ░ ░ ░ ▓ ░ ░
3  ░ ░ ░ ░ ░ ░ ░ ░
2  ░ ░ ░ ░ ░ ░ ░ ░
1  ░ ░ ░ ░ ░ ░ ░ ░
   A B C D E F G H
8  ░ ░ ░ ░ ░ ░ ░ ▓
7  ░ ░ ░ ░ ░ ░ ▓ ░
6  ░ ░ ░ ░ ░ ▓ ░ ░
5  ░ ░ ░ ░ ▓ ░ ░ ░
4  ░ ░ ░ ▓ ░ ░ ░ ░
3  ░ ░ ▓ ░ ░ ░ ░ ░
2  ░ ▓ ░ ░ ░ ░ ░ ░
1  ▓ ░ ░ ░ ░ ░ ░ ░
   A B C D E F G H
8  ░ ░ ░ ░ ░ ▓ ░ ░
7  ░ ░ ░ ░ ▓ ░ ░ ░
6  ░ ░ ░ ▓ ░ ░ ░ ░
5  ░ ░ ▓ ░ ░ ░ ░ ░
4  ░ ▓ ░ ░ ░ ░ ░ ░
3  ░ ░ ░ ░ ░ ░ ░ ░
2  ░ ░ ░ ░ ░ ░ ░ ░
1  ░ ░ ░ ░ ░ ░ ░ ░
   A B C D E F G H


In [16]:
board.reset_bb()
board.minus9(sq.d4)
pretty_print_bb(board.bb)
board.reset_bb()
board.minus9(sq.h8)
pretty_print_bb(board.bb)
board.reset_bb()
board.minus9(sq.h2)
pretty_print_bb(board.bb)

8  ░ ░ ░ ░ ░ ░ ░ ░
7  ░ ░ ░ ░ ░ ░ ░ ░
6  ░ ░ ░ ░ ░ ░ ░ ░
5  ░ ░ ░ ░ ░ ░ ░ ░
4  ░ ░ ░ ▓ ░ ░ ░ ░
3  ░ ░ ▓ ░ ░ ░ ░ ░
2  ░ ▓ ░ ░ ░ ░ ░ ░
1  ▓ ░ ░ ░ ░ ░ ░ ░
   A B C D E F G H
8  ░ ░ ░ ░ ░ ░ ░ ▓
7  ░ ░ ░ ░ ░ ░ ▓ ░
6  ░ ░ ░ ░ ░ ▓ ░ ░
5  ░ ░ ░ ░ ▓ ░ ░ ░
4  ░ ░ ░ ▓ ░ ░ ░ ░
3  ░ ░ ▓ ░ ░ ░ ░ ░
2  ░ ▓ ░ ░ ░ ░ ░ ░
1  ▓ ░ ░ ░ ░ ░ ░ ░
   A B C D E F G H
8  ░ ░ ░ ░ ░ ░ ░ ░
7  ░ ░ ░ ░ ░ ░ ░ ░
6  ░ ░ ░ ░ ░ ░ ░ ░
5  ░ ░ ░ ░ ░ ░ ░ ░
4  ░ ░ ░ ░ ░ ░ ░ ░
3  ░ ░ ░ ░ ░ ░ ░ ░
2  ░ ░ ░ ░ ░ ░ ░ ▓
1  ░ ░ ░ ░ ░ ░ ▓ ░
   A B C D E F G H


In [17]:
board.reset_bb()
board.minus1(sq.f5)
pretty_print_bb(board.bb)

8  ░ ░ ░ ░ ░ ░ ░ ░
7  ░ ░ ░ ░ ░ ░ ░ ░
6  ░ ░ ░ ░ ░ ░ ░ ░
5  ▓ ▓ ▓ ▓ ▓ ▓ ░ ░
4  ░ ░ ░ ░ ░ ░ ░ ░
3  ░ ░ ░ ░ ░ ░ ░ ░
2  ░ ░ ░ ░ ░ ░ ░ ░
1  ░ ░ ░ ░ ░ ░ ░ ░
   A B C D E F G H


In [18]:
board.reset_bb()
board.minus7(sq.d5)
pretty_print_bb(board.bb)

8  ░ ░ ░ ░ ░ ░ ░ ░
7  ░ ░ ░ ░ ░ ░ ░ ░
6  ░ ░ ░ ░ ░ ░ ░ ░
5  ░ ░ ░ ▓ ░ ░ ░ ░
4  ░ ░ ░ ░ ▓ ░ ░ ░
3  ░ ░ ░ ░ ░ ▓ ░ ░
2  ░ ░ ░ ░ ░ ░ ▓ ░
1  ░ ░ ░ ░ ░ ░ ░ ▓
   A B C D E F G H


In [19]:
board.reset_bb()
board.minus7(sq.b8)
pretty_print_bb(board.bb)

8  ░ ▓ ░ ░ ░ ░ ░ ░
7  ░ ░ ▓ ░ ░ ░ ░ ░
6  ░ ░ ░ ▓ ░ ░ ░ ░
5  ░ ░ ░ ░ ▓ ░ ░ ░
4  ░ ░ ░ ░ ░ ▓ ░ ░
3  ░ ░ ░ ░ ░ ░ ▓ ░
2  ░ ░ ░ ░ ░ ░ ░ ▓
1  ░ ░ ░ ░ ░ ░ ░ ░
   A B C D E F G H


In [20]:
board.reset_bb()
board.minus7(sq.g8)
pretty_print_bb(board.bb)

8  ░ ░ ░ ░ ░ ░ ▓ ░
7  ░ ░ ░ ░ ░ ░ ░ ▓
6  ░ ░ ░ ░ ░ ░ ░ ░
5  ░ ░ ░ ░ ░ ░ ░ ░
4  ░ ░ ░ ░ ░ ░ ░ ░
3  ░ ░ ░ ░ ░ ░ ░ ░
2  ░ ░ ░ ░ ░ ░ ░ ░
1  ░ ░ ░ ░ ░ ░ ░ ░
   A B C D E F G H


In [21]:
board.reset_bb()
board.minus8(sq.d5)
pretty_print_bb(board.bb)

8  ░ ░ ░ ░ ░ ░ ░ ░
7  ░ ░ ░ ░ ░ ░ ░ ░
6  ░ ░ ░ ░ ░ ░ ░ ░
5  ░ ░ ░ ▓ ░ ░ ░ ░
4  ░ ░ ░ ▓ ░ ░ ░ ░
3  ░ ░ ░ ▓ ░ ░ ░ ░
2  ░ ░ ░ ▓ ░ ░ ░ ░
1  ░ ░ ░ ▓ ░ ░ ░ ░
   A B C D E F G H


In [22]:
board.reset_bb()
board.minus1(sq.d5)
pretty_print_bb(board.bb)

8  ░ ░ ░ ░ ░ ░ ░ ░
7  ░ ░ ░ ░ ░ ░ ░ ░
6  ░ ░ ░ ░ ░ ░ ░ ░
5  ▓ ▓ ▓ ▓ ░ ░ ░ ░
4  ░ ░ ░ ░ ░ ░ ░ ░
3  ░ ░ ░ ░ ░ ░ ░ ░
2  ░ ░ ░ ░ ░ ░ ░ ░
1  ░ ░ ░ ░ ░ ░ ░ ░
   A B C D E F G H


In [23]:
board.reset_bb()
x = board.knight_attacks(sq.h6)
pretty_print_bb(x)
board.reset_bb()
x = board.knight_attacks(sq.h1)
pretty_print_bb(x)
board.reset_bb()
x = board.knight_attacks(sq.a1)
pretty_print_bb(x)
board.reset_bb()
x = board.knight_attacks(sq.a8)
pretty_print_bb(x)
board.reset_bb()
x = board.knight_attacks(sq.d1)
pretty_print_bb(x)
board.reset_bb()
x = board.knight_attacks(sq.f3)
pretty_print_bb(x)
x = board.knight_attacks(sq.c6)
pretty_print_bb(x)

8  ░ ░ ░ ░ ░ ░ ▓ ░
7  ░ ░ ░ ░ ░ ▓ ░ ░
6  ░ ░ ░ ░ ░ ░ ░ ▓
5  ░ ░ ░ ░ ░ ▓ ░ ░
4  ░ ░ ░ ░ ░ ░ ▓ ░
3  ░ ░ ░ ░ ░ ░ ░ ░
2  ░ ░ ░ ░ ░ ░ ░ ░
1  ░ ░ ░ ░ ░ ░ ░ ░
   A B C D E F G H
8  ░ ░ ░ ░ ░ ░ ░ ░
7  ░ ░ ░ ░ ░ ░ ░ ░
6  ░ ░ ░ ░ ░ ░ ░ ░
5  ░ ░ ░ ░ ░ ░ ░ ░
4  ░ ░ ░ ░ ░ ░ ░ ░
3  ░ ░ ░ ░ ░ ░ ▓ ░
2  ░ ░ ░ ░ ░ ▓ ░ ░
1  ░ ░ ░ ░ ░ ░ ░ ▓
   A B C D E F G H
8  ░ ░ ░ ░ ░ ░ ░ ░
7  ░ ░ ░ ░ ░ ░ ░ ░
6  ░ ░ ░ ░ ░ ░ ░ ░
5  ░ ░ ░ ░ ░ ░ ░ ░
4  ░ ░ ░ ░ ░ ░ ░ ░
3  ░ ▓ ░ ░ ░ ░ ░ ░
2  ░ ░ ▓ ░ ░ ░ ░ ░
1  ▓ ░ ░ ░ ░ ░ ░ ░
   A B C D E F G H
8  ▓ ░ ░ ░ ░ ░ ░ ░
7  ░ ░ ▓ ░ ░ ░ ░ ░
6  ░ ▓ ░ ░ ░ ░ ░ ░
5  ░ ░ ░ ░ ░ ░ ░ ░
4  ░ ░ ░ ░ ░ ░ ░ ░
3  ░ ░ ░ ░ ░ ░ ░ ░
2  ░ ░ ░ ░ ░ ░ ░ ░
1  ░ ░ ░ ░ ░ ░ ░ ░
   A B C D E F G H
8  ░ ░ ░ ░ ░ ░ ░ ░
7  ░ ░ ░ ░ ░ ░ ░ ░
6  ░ ░ ░ ░ ░ ░ ░ ░
5  ░ ░ ░ ░ ░ ░ ░ ░
4  ░ ░ ░ ░ ░ ░ ░ ░
3  ░ ░ ▓ ░ ▓ ░ ░ ░
2  ░ ▓ ░ ░ ░ ▓ ░ ░
1  ░ ░ ░ ▓ ░ ░ ░ ░
   A B C D E F G H
8  ░ ░ ░ ░ ░ ░ ░ ░
7  ░ ░ ░ ░ ░ ░ ░ ░
6  ░ ░ ░ ░ ░ ░ ░ ░
5  ░ ░ ░ ░ ▓ ░ ▓ ░
4  ░ ░ ░ ▓ ░ ░ ░ ▓
3  ░ ░ ░ ░ ░ ▓ ░ ░
2  ░ ░ ░ ▓ ░ ░ ░ ▓
1  ░ ░ ░ ░ ▓

In [24]:
x = np.array([0,1,1,0])
y = np.array([1,1,0,0])
z = np.array([0,1,1,1])

In [25]:
x | y | z

array([1, 1, 1, 1])

In [26]:
board.knight_bbs[sq.c6]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0],
      dtype=int8)

In [27]:
# what pieces does a white knight on f5 attack if black is in the starting position
pretty_print_bb(board.knight_bbs[sq.f5] & board.black_pieces_bb)

8  ░ ░ ░ ░ ░ ░ ░ ░
7  ░ ░ ░ ░ ▓ ░ ▓ ░
6  ░ ░ ░ ░ ░ ░ ░ ░
5  ░ ░ ░ ░ ░ ░ ░ ░
4  ░ ░ ░ ░ ░ ░ ░ ░
3  ░ ░ ░ ░ ░ ░ ░ ░
2  ░ ░ ░ ░ ░ ░ ░ ░
1  ░ ░ ░ ░ ░ ░ ░ ░
   A B C D E F G H


In [28]:
board.knight_bbs[sq.f5] & board.black_pieces_bb

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int8)

In [29]:
for i in range(1, 8):
    print(i)

1
2
3
4
5
6
7
